package algebra.curves.barreto_lynn_scott.abstract_bls_parameters;

import algebra.fields.abstractfieldparameters.AbstractFp12_2Over3Over2_Parameters;

public abstract class AbstractBLSFq12Parameters extends AbstractFp12_2Over3Over2_Parameters {}
